# Generated by Django 3.1.7 on 2022-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='writer_authorized',
        ),
        migrations.AddField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, default='default-header.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('reader', 'reader'), ('writer', 'writer'), ('moderator', 'moderator'), ('data uploader', 'data uploader')], default='reader', max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
